### ISSUE TITLE
Plex service name not working

### ISSUE THREAD

**Issue by modem7** [Drewpeifer/medialytics#13]
Heya, 

External domain works, but for some odd reason, internal Docker DNS service name does not.

```yaml
  medialytics:
    image: ghcr.io/drewpeifer/medialytics:latest
    container_name: Medialytics
    environment:
      - SERVER_IP=plex
      - SERVER_TOKEN=$PLEXTOKEN
    networks:
      pihole:
        ipv4_address: '172.22.0.111'
    ports:
      - "27015:80"
    depends_on:
      - plex
    restart: always
```

Is there any way to get this working? Seems odd going out of the network just to come back in to get the relevant stats.

I can use the internal server IP (http://192.168.etc.etc:port), but given that Docker can work in this way, it may be worthwhile investigating to see if it can be used.
